### ISSUE TITLE
Array bug | rewrite failed, key does not exist

### ISSUE THREAD

**Issue by t1k3** [larapack/config-writer#14] opened 2016-12-06 12:56 UTC
Example 1: 
```
app.php > 'locales' => ['en'],
$locales = ['en-GB'];
Config::write('app', ['locales' => $locales]);
```
Exception in Repository.php line 146:
Unable to rewrite key "locales.0" in config, rewrite failed

Example 2: 
```
app.php > 'locales' => ['en'],
$locales = ['en', 'en-GB'];
Config::write('app', ['locales' => $locales]);
```
Exception in Repository.php line 137:
Unable to rewrite key "locales.1" in config, does it exist?

**Comment by marktopper** [comment] 2017-02-09 12:36
Duplicate of #11

**Closed as completed by marktopper** 2017-02-09 12:36 UTC
